#!/bin/sh

# Usage:
#	 curl -sL github.com/wstein/setup/raw/master/dev-base | sh
# or
#	 curl -sL github.com/wstein/setup/raw/develop/dev-base | sh
# or shorthand for develop branch:
#	 curl -sL git.io/devbase | sh
#

set -eu

main() {
	cd $HOME

	create_bin_folder
	create_config_folder

	$HOME/bin/install-minimal
	$HOME/bin/setup-user

	setup_zsh

  echo
	/usr/local/bin/neofetch
}

setup_zsh() {
	CMD_CHSH=$(command -v lchsh || command -v chsh || true)

	if [ -n "$CMD_CHSH" ]; then
		command -v zsh | sudo $CMD_CHSH $(whoami)
	fi

  # install zsh plugins ;-)
	zsh -il -c true
}

create_bin_folder() {
	echo creating bin folder...

	# check to create ~/bin
	! test -d $HOME/bin && mkdir $HOME/bin

	cd "$HOME/bin"
	git init
	git symbolic-ref HEAD refs/heads/main # use main instead of master branch
	git remote add origin https://github.com/wstein/bin
	git pull origin main
	cd "$HOME"
}

create_config_folder() {
	echo creating .config folder...

	# check to create ~/.config
	! test -d $HOME/.config && mkdir $HOME/.config

	cd "$HOME/.config"
	git init
	git symbolic-ref HEAD refs/heads/main # use main instead of master branch
	git remote add origin https://github.com/wstein/.config
	git pull origin main
	cd "$HOME"
}

padd() {
	# SUDO is only set, if sudo is actually installed!
	SUDO=$(command -v sudo || true)

	PACKAGES="$@"

	PKG_MANAGER_PATH=$({ command -v apk || command -v apt || command -v dnf || command -v yum || command -v zypper || command -v pacman || command -v eopkg-cli; })

	# /usr/bin/dnf -> dnf
	PKG_MANAGER=${PKG_MANAGER_PATH##*/}

	case "$PKG_MANAGER" in
	apk)
		$SUDO apk add $PACKAGES
		;;

	apt)
		$SUDO apt -y update
		$SUDO apt -y install $PACKAGES
		;;

	dnf | yum)
		$SUDO $PKG_MANAGER -y install $PACKAGES
		;;

	eopkg-cli)
		$SUDO eopkg-cli update-repo
		$SUDO eopkg-cli -y install $PACKAGES
		;;
	
	pacman)
		$SUDO pacman -Sy --noconfirm $PACKAGES glibc
		;;

	zypper)
		$SUDO zypper install -y $PACKAGES
		;;

	*)
		echo "Fatal Error: No supported package manager found!"
		exit 1
		;;

	esac
}

main "$@"
