#!/bin/sh

# Usage:
#	 curl -sL github.com/wstein/setup/raw/master/dev-base | sh
# or
#	 curl -sL github.com/wstein/setup/raw/develop/dev-base | sh
# or shorthand for develop branch:
#	 curl -sL git.io/devbase | sh
#

set -eu

main() {
	cd ~

	clone_repositories

	$HOME/bin/install-minimal
	$HOME/bin/setup-user

	change_default_shell

	# install zsh plugins ;-)
	zsh -il -c true

	neofetch
}

change_default_shell() {
	CMD_CHSH=$(command -v lchsh || command -v chsh || true)

	if [ -n "$CMD_CHSH" ]; then
		command -v zsh | $CMD_CHSH $(whoami)
	fi
}

clone_repositories() {
	if ! [ -d $HOME/.config ]; then
		command -v git || padd git
		git clone https://github.com/wstein/.config
	fi
	if ! [ -d $HOME/bin ]; then
		command -v git || padd git
		test -d $HOME/bin || git clone https://github.com/wstein/bin
	fi
}

padd() {
	# SUDO is only set, if sudo is actually installed!
	SUDO=$(command -v sudo || true)

	PACKAGES="$@"

	PKG_MANAGER_PATH=$({ command -v apk || command -v apt || command -v dnf || command -v yum || command -v zypper || command -v pacman; })

	# /usr/bin/dnf -> dnf
	PKG_MANAGER=${PKG_MANAGER_PATH##*/}

	case "$PKG_MANAGER" in
	apk)
		$SUDO apk add $PACKAGES
		;;

	apt)
		$SUDO apt -y update
		$SUDO apt -y install $PACKAGES
		;;

	dnf)
		$SUDO dnf -y install $PACKAGES
		;;

	pacman)
		$SUDO pacman -Sy --noconfirm $PACKAGES glibc
		;;

	zypper)
		$SUDO zypper install -y $PACKAGES
		;;

	*)
		echo "Fatal Error: No supported package manager found!"
		exit 1
		;;

	esac
}

main "$@"
