#!/usr/env sh
# install:
#   curl -L https://github.com/wstein/setup/raw/develop/setup-zsh | zsh
#
# requried packages: curl, git, zsh and procps!
#
#   apk add curl git procps zsh
#   apt update && apt -y install curl git procps zsh
#   dnf install -y curl git procps zsh
#   pacman -Sy curl git procps zsh
#   zypper install curl git procps zsh
#
# OPTIONAL: exa git-extras neovim ripgrep tmux

set -eu

main() {
	echo setup zsh...
	create_folders
	dl_files https://github.com/wstein/setup/raw/develop
	zsh -lic true
}

create_folders() {
	test -d $HOME/.config/p10k || mkdir --parents $HOME/.config/p10k
	test -d $HOME/bin || mkdir --parents $HOME/bin
	test -d $HOME/.local/bin || mkdir --parents $HOME/.local/bin
}

dl_files() {
	curl -fsSL https://git.io/antigen >"$HOME/.local/bin/antigen.zsh"
	curl -fsSL $1/.zshrc >$HOME/.zshrc
	curl -fsSL $1/.config/p10k/lean-ansi.zsh >$HOME/.config/p10k/lean-ansi.zsh
	curl -fsSL $1/.config/p10k/lean-unicode.zsh >$HOME/.config/p10k/lean-unicode.zsh
	curl -fsSL $1/.config/p10k/rainbow-ansi.zsh >$HOME/.config/p10k/rainbow-ansi.zsh
	curl -fsSL $1/.config/p10k/rainbow-unicode.zsh >$HOME/.config/p10k/rainbow-unicode.zsh
	curl -fsSL $1/.config/p10k/rainbow-dracula-ansi.zsh >$HOME/.config/p10k/rainbow-dracula-ansi.zsh
	curl -fsSL $1/.config/p10k/rainbow-dracula-unicode.zsh >$HOME/.config/p10k/rainbow-dracula-unicode.zsh
}

main "$@"
