#!/bin/sh

set -e 

TERMINUS_RPM=$(wget https://github.com/Eugeny/terminus/releases/download/v1.0.112/terminus-1.0.112-linux.rpm --directory-prefix=/tmp -nv 2>&1 | cut -d\" -f2)
GITKRAKEN_RPM=$(wget https://release.axocdn.com/linux/gitkraken-amd64.rpm --directory-prefix=/tmp -nv 2>&1 | cut -d\" -f2)
TOOLBOX_TGZ=$(wget https://download-cf.jetbrains.com/toolbox/jetbrains-toolbox-1.17.6802.tar.gz --directory-prefix=/tmp -nv 2>&1 | cut -d\" -f2)
USER_BIN=~/bin

test ! -d $USER_BIN && mkdir $USER_BIN
tar -xzv --strip-components=1 -C $USER_BIN -f $TOOLBOX_TGZ

# setup vscode repo
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

sudo dnf -y install hub gitk git-gui htop screen neovim xrdp keepassxc toolbox code fira-code-fonts zsh util-linux-user java-11-openjdk-devel $TERMINUS_RPM $GITKRAKEN_RPM

sudo chsh -s $(which zsh) $USERNAME

sudo systemctl enable --now xrdp
sudo firewall-cmd --add-port=3389/tcp --permanent
sudo firewall-cmd --reload

mkdir --parent ~/.config/Code/User
cat <<EOF > ~/.config/Code/User/settings.json
{
    "editor.fontFamily": "'Fira Code','Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
    "editor.fontLigatures": true,
    "editor.formatOnSave": true,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false
}
EOF

curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh && 
sed -ie "s/^ZSH_THEME=\".*\"/ZSH_THEME=\"avit\"/" ~/.zshrc &&
sed -ie "s/^plugins=\".*\"/plugins=\"(git docker docker-compose)\"/" ~/.zshrc


