#!/bin/sh

set -e 

# install 
sudo dnf -y install hyperv-daemons hyperv-tools hypervfcopyd hypervkvpd hypervvssd xrdp tigervnc-server-minimal

# Set basic session to 1920x1080 
sudo grubby --update-kernel=ALL --args="video=hyperv_fb:1920x1080"

# Install Hyper-V Enhanced Session Mode
# Load the Hyper-V kernel module
if ! [ -f "/etc/modules-load.d/hv_sock.conf" ] || [ "$(cat /etc/modules-load.d/hv_sock.conf | grep hv_sock)" = ""  ]; then
  echo "hv_sock" | sudo tee -a /etc/modules-load.d/hv_sock.conf > /dev/null
fi

# Configure xrdp
sudo sed -i -e "/^port=3389/c\port=vsock://-1:3389" \
            -e "/^use_vsock=.*/c\use_vsock=false" \
            -e "/^security_layer=.*/c\security_layer=rdp" \
            -e "/^crypt_level=.*/c\crypt_level=none" \
            -e "/^bitmap_compression=.*/c\bitmap_compression=false" \
            -e "/^max_bpp=.*/c\max_bpp=24" /etc/xrdp/xrdp.ini

sudo sed -i "/^X11DisplayOffset=.*/c\X11DisplayOffset=0" /etc/xrdp/sesman.ini
if ! [ -f /etc/X11/Xwrapper.config ] || [ "$(cat /etc/X11/Xwrapper.config | grep allowed_users=anybody)" = "" ]; then
  echo "allowed_users=anybody" | sudo tee -a /etc/X11/Xwrapper.config > /dev/null
fi

sudo systemctl enable --now xrdp

