FROM wstein/ubuntu

RUN apt-get -y install gpg &&\
    curl -fsSL https://dist.crystal-lang.org/apt/setup.sh | bash &&\
    curl -fsSL "https://keybase.io/crystal/pgp_keys.asc" | apt-key add - &&\
    apt-get update
RUN apt-get -y install crystal

RUN apt-get -y install libgmp-dev libsqlite3-dev libssl-dev libxml2-dev libyaml-dev libz-dev

VOLUME [ "/data/crystal" ]
WORKDIR /data/crystal
